(ns p2)

;Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
;1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
;By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
(defn finbo-gen [i l]
  (loop [x i list l]
    ;(println x)
    ;(println list)
    (let [next (+ (first list) (nth list 1))]
      (if (> x next)
        (recur x (conj list next))
        list
        )
      )
    )
  )

(defn sumofEvenFibo [x]
  (reduce + 0 (filter even? (finbo-gen x (list 2 1)))
          )
  )

(defn problem2 []
  (sumofEvenFibo 4000000))
